### ISSUE TITLE
关于微信小程序的样式问题

### ISSUE THREAD

**Issue by xueelf** [ijry/uview-plus#114]
引入组件库后在微信开发工具一直提示 `Some selectors are not allowed in component wxss` 的警告

经排查，定位到问题出自 `libs/css/components.scss` 的下列样式导致：

```scss
/* #ifndef APP-NVUE */
view, scroll-view, swiper-item {
  display: flex;
  flex-direction: column;
  flex-shrink: 0;
  flex-grow: 0;
  flex-basis: auto;
  align-items: stretch;
  align-content: flex-start;
}
/* #endif */
```

查阅了相关文档，在微信 [组件样式](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/wxml-wxss.html#%E7%BB%84%E4%BB%B6%E6%A0%B7%E5%BC%8F) 一览中规定，禁止在 **组件中** 使用标签名选择器，提示该样式在组件中也 **不会生效**。

然而实际上 `flex-direction: column` 的样式是生效的，目前来讲在微信小程序上除了有警告，是没任何影响的。但出于官方文档的描述，不排除以后会出现一系列不确定因素，看后续针对此处如何做出改动
